### ISSUE TITLE
Multiple Selected items can't fit into the dropdown display box and gets hidden when the tree appears.

### ISSUE THREAD

**Issue by prawnz** [lukemurray/NgHierarchicalSelector#5]
![image of issue](https://cloud.githubusercontent.com/assets/3827044/6724220/830168ee-ce2e-11e4-87f6-0bd901690a37.png)

Is this by design or a bug from Bootstrap?

**Comment by lukemurray** [comment]
Not by design, a known issue in the control. It's on my list of things to fix. PRs welcome :)
