### ISSUE TITLE
Postback issue

### ISSUE THREAD

**Issue by prawnz** [lukemurray/NgHierarchicalSelector#6]
I'm trying to embed this to a SharePoint webpart control however the control is causing the page to refresh everytime. Is there anyway to prevent it posting back?

**Comment by prawnz** [comment]
I've solve this.. in the template you need to put type="button" for all button tags.

**Comment by lukemurray** [comment]
Sorry, are you cahnging the template of this control?

**Comment by prawnz** [comment]
In my instance where it is causing postback when embedded into a ASP.Net
web application, yes unless there is another easier way out. I didn't do
any check-in to the code from GitHub.

Also I found a way to ensure that the selected items don't overlap on top
of each other.

I achieved it with a css override

.selected-item-close

{

margin-bottom:4px !important;

 }

if you find that works you could update your control with that.

Best Regards
Nicholas Ang
0411377662
Skype/GTalk/MSN : Prawnz@gmail.com

**Comment by lukemurray** [comment]
Could you post a screenshot of the over lapping items?

Also you mean that clicking the button for the drop down was causing a post back without type=button ? Which browser was this in?

Thanks

**Comment by prawnz** [comment]
Quoting
"Also you mean that clicking the button for the drop down was causing a
post back without type=button ? Which browser was this in?"

This is in IE when used in a ASP.Net Web application

Quoting
"Could you post a screenshot of the over lapping items?"
This was from another issue that i raised before. It is on your to do list.

Best Regards
Nicholas Ang
0411377662
Skype/GTalk/MSN : Prawnz@gmail.com

**Comment by lukemurray** [comment]
Thanks, I've updated it with type=button and I;ve fix the other issue.
