### ISSUE TITLE
How to enable auto-complete and searching?

### ISSUE THREAD

**Issue by jshbrntt** [lukemurray/NgHierarchicalSelector#9]
I can't docs or an example that shows how to enable searching or auto-complete of the treeview?

**Comment by lukemurray** [comment]
This feature is currently not supported. You'll see in the readme that autocomplete functionality in under the Todo section.

I'll leave this open as an issue to track it. Pull requests are welcome as I haven't had much time to spend on this as of late.

**Comment by Clan-Utility** [comment]
Fantastic work!
+1 for autocompletion!

**Comment by kadosh1000** [comment]
Is there any progress on that feature?

**Comment by corydorning** [comment]
wondering the same thing. dealing with long lists and not having autocomplete makes this a tougher sell.

**Comment by lukemurray** [comment]
I do agree. Sorry I haven't had the time I'd like to add some more functionality to this. Pull requests are always welcome. 

Otherwise I'm hoping to get to it early next year as we may need it where I work.
